[project]
name = "deep-image-stego"
version = "0.1.0"
description = "深度图像信息隐藏与提取框架"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "林裕斌" },
  { name = "曾科" },
  { name = "田承金" },
  { name = "吕善翔" }
]

[project.scripts]
deep_image_stego = "deep_image_stego.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
